### PR TITLE
1.20.5 options background missing texture fix

### LINKED ISSUE #18: missing options background texture in 1.20.5+
with the removal of `options_background`, the RSMM options background is now missing a texture

```
The options_background and the light_dirt_background textures have been removed.
Instead, menu_background is used as the background of screens, while menu_list_background is used for the background of lists.
```
[(source)](https://minecraft.wiki/w/Java_Edition_1.20.5#:~:text=The%20options_background%20and%20the%20light_dirt_background%20textures%20have%20been%20removed)

# result
image

the simple fix is to replace the background with `inworld_menu_list_background`, but the translucent texture exposes the list elements drawn behind the top & bottom separators:

image

> don't mind the LOLCAT menus

still, i think this is an improvement. i'll open a PR shortly (and include this change in my upcoming 1.21 update PR)

### PR DESCRIPTION
**Pull request by emilyavi**
#18 
should the mod version be bumped up?

### CODE REVIEW

File: src/main/java/redstone/multimeter/client/gui/Texture.java [hunk 1]
```diff
@@ -4,7 +4,7 @@
 
 public class Texture {
 
-	public static final Texture OPTIONS_BACKGROUND    = new Texture(new ResourceLocation("textures/gui/options_background.png"), 16, 16);
+	public static final Texture OPTIONS_BACKGROUND    = new Texture(new ResourceLocation("textures/gui/inworld_menu_list_background.png"), 16, 16);
```
Comment (SpaceWalkerRS) [inline src/main/java/redstone/multimeter/client/gui/Texture.java:7]: IMO `menu_background` should be used instead, so as to keep the same aesthetic as previous versions. As you said in the issue report, this solution results in otherwise hidden elements being exposed, and I wouldn't accept it without that being fixed too.

**Review by SpaceWalkerRS — CHANGES_REQUESTED** [review]

File: src/main/java/redstone/multimeter/client/gui/Texture.java (hunk 1 above)
Comment (emilyavi) [reply src/main/java/redstone/multimeter/client/gui/Texture.java:7]: since this was a change made to all of the game's backgrounds, keeping the old aesthetic would make it inconsistent with the game, which i think would feel more out of place.
`menu_background` is also a translucent texture and results in the same issue
i chose `inworld_menu_list_background` specifically because there is a keybind for opening the config while in-game (i didn't realize you can also open it from the main menu, so maybe the non-in-game variant would be better)

Comment (SpaceWalkerRS) [reply src/main/java/redstone/multimeter/client/gui/Texture.java:7]: I poked around a little and it seems that keeping the old aesthetic would be more of a pain than this, so I'll just go along with it

**Review by SpaceWalkerRS — APPROVED** [review]
